### cloudbuild.yaml for CI/CD Pipeline

### Set up substitutions for dynamic values
substitutions:
  _PROJECT_ID: qwiklabs-gcp-01-685584958cde
  _REGION: us-west1
  _SERVICE_NAME: inventory-api
  _REPOSITORY: cloud-run-source-deploy
  _IMAGE_NAME: us-west1-docker.pkg.dev/qwiklabs-gcp-01-685584958cde/inventory-app-git-link/chat

steps:
  ### Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build-Docker-Image
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'

  ### Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-to-Artifact-Registry
    args:
      - 'push'
      - '${_IMAGE_NAME}:$COMMIT_SHA'

  ### Step 3: Deploy the new image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy-to-Cloud-Run
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
